name: Publish Doxygen Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install Doxygen and Graphviz
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Run CMake
      run: cmake -B build -DBUILD_DOC=ON

    - name: Create Documentation
      uses: mattnotmitt/doxygen-action@v1.12.0
      with:
        doxyfile-path: "Doxyfile.doxygen-doc"
        working-directory: "build/doxygen"

    - name: Publish Documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/doxygen/html
